name: Build & Deploy .NET 7 Project to Plesk

# Push yapıldığında çalışacak
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Linux runner kullanıyoruz, SCP/SFTP sorunsuz çalışacak
    runs-on: ubuntu-latest

    steps:
    # Repo’yu checkout et
    - name: Checkout repository
      uses: actions/checkout@v3

    # .NET 7 kurulumu
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # Bağımlılıkları yükle
    - name: Restore dependencies
      run: dotnet restore AMMasterProject/AMMasterProject.csproj

    # Projeyi build et
    - name: Build project
      run: dotnet build AMMasterProject/AMMasterProject.csproj --configuration Release --no-restore

    # Projeyi publish et
    - name: Publish project
      run: dotnet publish AMMasterProject/AMMasterProject.csproj --configuration Release --output ./publish

    # Publish edilen dosyaları SFTP ile Plesk server’a gönder
    - name: Deploy via SFTP to Plesk
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PLESK_HOST }}
        username: ${{ secrets.PLESK_USER }}
        password: ${{ secrets.PLESK_PASS }}
        port: 22
        source: "./publish/*"
        target: "/httpdocs/"
