name: Build & Deploy .NET Project to Plesk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy via SFTP to Plesk
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PLESK_HOST }}
        username: ${{ secrets.PLESK_USER }}
        password: ${{ secrets.PLESK_PASS }}
        port: 22
        source: "./publish/*"
        target: "/httpdocs/"
